### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by GeorgiaGage** [torgeir/cljs-workshop#10]
I loved playing with this at NDC Oslo and wanted to use it myself so tried to install it. I encountered a couple of problems when installing on Linux (Ubunutu) but managed to fix them. Here's what I learnt...

### Linux

- Install Java 8.
- Install the package `Calva: Clojure & Clojurescript Interactive Programming` in Visual Studio Code.
- Install Clojure: Follow the instructions on closure site (https://clojure.org/guides/getting_started) and install in home directory.
    Trying to install it via command line with

```sh
DO NOT USE: sudo apt install clojure
```

resulted in missing files (the -Sdep file) when trying to run.
Instructions on Clojure's site:

1. Ensure that the following dependencies are installed: bash, curl, rlwrap, and Java.

2. Use the linux-install script to download and run the install, which will create /usr/local/bin/clj, /usr/local/bin/clojure, and /usr/local/lib/clojure:

```sh
curl -O https://download.clojure.org/install/linux-install-1.10.1.447.sh

chmod +x linux-install-1.10.1.447.sh

sudo ./linux-install-1.10.1.447.sh
```
To test that you're all good with Clojure, type 'clj' into the CL. For some reason typing 'clojure' doesn't work. 

Thanks for writing such beautiful software! I'm going to play with it for days and cover my house in Clojure artwork.

**Comment by torgeir** [comment]
Hey! I'm so glad you enjoyed it! 

Yeah, linux was a rough path the last time I tried it.. but I see their installation process seems to have improved since then. I'll definitely add that as a section in the readme for linux users.

> Thanks for writing such beautiful software! I'm going to play with it for days and cover my house in Clojure artwork.

I think that sounds like a fantastic idea, go for it! 🖼👏 Don't hesitate to hit us up with questions if you're stuck or anything seems unclear, or even share your creations.

**Comment by torgeir** [comment]
Added a [section on using linux to the readme](https://github.com/torgeir/cljs-workshop/blob/6effccc58f2370cf8a7256338e233f0012a5f7b8/readme.md#linux) as per your notes ✅
